# Site setings
name: 'nrasch.github.io'
description: '404 Clever Blog Title Not Found'
meta_description: '404 Clever Blog Title Not Found'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://nrasch.github.io/
disqus: ''
mailchimp_url: ''
cover_image: bc_1.jpg
# Add your GA Tracking Id
ga_analytics: 


# Author
author:
  name: 'Nathan Rasch'
  image: 'nathan_rasch.jpg'
  greetings: 'Welcome'
  description: 'My name is Nathan Rasch. I'm a software developer and leader living in Colorado Springs, CO.'
  bio: 'Nathan has worked throughout his career as leader, project manager, and software developer.  He has an MBA, a BA in Mathematics, and is a Certified ScrumMaster (CSM) and PMI Certified Associate in Project Management (CAPM).'

# Contact form setings
email: nathan@obsidiantech.net
contact_page_description: "Horace theme comes with a contact form built-in. You can use this form with Formspree service and get up to 50 submissions for free. Also, you can easily switch to another service if you want."
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
github: 'nrasch'
linkedin: 'nathanrasch'

# Navigation
navigation:
  - text: About
    url: /about/
  - text: Contact Me
    url: /contact/

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
