# Site setings
name: 'nrasch.github.io'
title: 'nrasch.github.io'
description: '404 Clever Blog Title Not Found'
meta_description: '404 Clever Blog Title Not Found'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl:
production_url: https://nrasch.github.io/
disqus: 'nrasch-github-io'
cover_image: bc_1.jpg
# Add your GA Tracking Id
ga_analytics: 'UA-146592450-1'


# Author
author:
  name: 'Nathan Rasch'
  image: 'nathan_rasch.jpg'
  greetings: 'Welcome'
  description: "My name is Nathan Rasch. I'm a software developer and organizational leader living in Colorado Springs, CO."
  bio: "Nathan has worked throughout his career as a leader, project manager, and software developer.  He has an MBA in Business Administration and BA in Mathematics.  Nathan is also a Certified ScrumMaster (CSM) and PMI Certified Associate in Project Management (CAPM)."

# Contact form setings
email: nathan@obsidiantech.net
contact_page_description: "Please enter your message details below."
thankyou_page_description: "Thank you.  Your message has been successfully sent."

# Social links
github: 'nrasch'
linkedin: 'nathanrasch'

# Navigation
navigation:
  - text: About
    url: /about.html
  - text: Contact Me
    url: /contact.html

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
